

BUILD_DIR 	:= src
MAIN_FILE 	:= main.c
OUTPUT_DIR	:= build
OUTPUT_FILE	:= main
TEST_DIR	:= test
TEST_FILE	:= test.c


all: run_test

run_test: 
	gcc $(TEST_DIR)/$(TEST_FILE) -o	run_test

clean:
	rm $(OUTPUT_DIR)/*
